version: "3"
services:
  mongo:
    image: 1landrada8/mongodb:latest
    build: ./
    ports:
      - 27017:27017

  backend:
    image: 1landrada8/backend
    build: ./backend/
    ports:
      - "5000:8000"
    depends_on:
      - "mongo"

  frontend:
    image: 1landrada8/dramafrontend
    mem_limit: 128m
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
    links:
      - backend

  nginx:
    image: 1landrada8/nginx
    build: ./nginx/
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"